import type { Metadata } from "next";
import { Alegreya, Cousine } from "next/font/google"
import "./globals.css";
import { NavBar } from "@/components/nav_bar"
import { Title } from "@/components/elements/title"

const serif = Alegreya({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-serif'
})
const mono = Cousine({ 
  weight: ["400"],
  display: 'swap', 
  subsets: ["latin"],
  variable: '--font-mono'
})
const globalClasses = 'font-serif'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='h-screen'>
      <body className={`
        ${serif.variable} 
        ${mono.variable} 
        font-serif p-5 h-full w-full flex flex-col
      `}>
        <Title/>
        <NavBar/>
        <main className='flex-[2_2_0%] overflow-hidden'>
          {children}
        </main>
      </body>
    </html>
  );
}
